### ISSUE TITLE
Which time buckets are we tracking?

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot-tracker#31]
@livlab In last week's review, we decided to get finer-grained time buckets for early on (if I remember right) -- was that reporting one second ("1s" buckets) up to 10 or 20 seconds? Or longer?

**Comment by livlab** [comment]
Here's what I'm thinking:
- 5 second increments up to 60 seconds
- 10 second increments from 60 seconds to 120 seconds
- 30 second increments from 120 seconds up

This is what I expect most graphics data to look like:
![image](https://cloud.githubusercontent.com/assets/1936365/12891903/ad088e86-ce57-11e5-9829-f3a24acc7407.png)

So, most activity between 0 and 2 minutes (this is an estimate based on timing myself reading about 10 stories to try to come up with a number so, n = 1, beware!), and then a bump at the long tail for people who leave their tab open, go away, come back and finish reading the story.

@brianboyer please chime in.

**Comment by livlab** [comment]
I am certain we'll have to adjust these buckets after we see what real data looks like, but I thought starting granular will show us more detail so we can calibrate better, rather than broader buckets where we'll miss variability (that I expect) between stories.

**Comment by brianboyer** [comment]
I'm good w/ whatever y'all think is best, as long as we keep in mind that
it might be useful to hit the same marks as the normal NPR analytics.

**Comment by hampelm** [comment]
We can record an increased granularity while still hitting NPR metrics. The current metrics I got from Tyler's code are:
- 10 second increments up to a minute
- 1 minute increments from 1-5 min 
- 5 minute increments from 5 min on

If we code the proposal:
- 5 second increments up to 60 seconds
- 10 second increments from 60 seconds to 120 seconds
- 30 second increments from 120 seconds

We'll still hit NPR marks (eg `10s`, `1m`, `30m` etc) and also have additional data with more details (`1m10s`).

One complication could be the number of events we log. NPR has a limit on the # that can be logged monthly, so a popular viz seen by a million people for 30 seconds would generate 6,000,000 additional events.

**Comment by brianboyer** [comment]
That many events _would_ piss off the team. How about we test for a week or
two w/ the granular numbers, see what we get, and make a ticket to
fine-tune/reduce them later, when we know better what we need?
