### ISSUE TITLE
Scroll depth phase 2

### ISSUE THREAD

**Issue by hampelm** [thecarebot/carebot-tracker#40]
Turn the scroll depth tracker from something that works through viz to something that can be dropped on any page.

Do we report to the NPR Viz property (easier) or to the NPR general property?

If we use the Viz property, this can be a standalone script that initializes the NPR viz GA property, then tracks and reports

If we use the main property, we need to know if GA is available by the point where we deploy our script. Otherwise, we'll need to wait or load it a second time ourself (not optimal).

In any case, it would probably just report the Seamus ID as the category.

**Comment by brianboyer** [comment]
not an issue anymore
